channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - absl-py=2.3.1
  - accelerate=1.12.0
  - adagio=0.2.6
  - adwaita-icon-theme=49.0
  - aenum=3.1.16
  - affine=2.4.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.2
  - aiosignal=1.4.0
  - alembic=1.17.2
  - alsa-lib=1.2.15.1
  - amply=0.1.6
  - annotated-types=0.7.0
  - anyio=4.12.0
  - aom=3.9.1
  - appdirs=1.4.4
  - archspec=0.2.5
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arpack=3.9.1
  - arrow=1.4.0
  - arviz=0.23.0
  - asttokens=3.0.1
  - astunparse=1.6.3
  - async-timeout=5.0.1
  - at-spi2-atk=2.38.0
  - at-spi2-core=2.40.3
  - atk-1.0=2.38.0
  - attr=2.5.2
  - attrs=25.4.0
  - audioread=3.0.1
  - autograd=1.8.0
  - autograd-gamma=0.5.0
  - aws-c-auth=0.8.6
  - aws-c-cal=0.8.7
  - aws-c-common=0.12.0
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.4
  - aws-c-http=0.9.4
  - aws-c-io=0.17.0
  - aws-c-mqtt=0.12.2
  - aws-c-s3=0.7.13
  - aws-c-sdkutils=0.2.3
  - aws-checksums=0.2.3
  - aws-crt-cpp=0.31.0
  - aws-sdk-cpp=1.11.510
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - backports.zstd=1.2.0
  - beautifulsoup4=4.14.3
  - binutils=2.45
  - binutils_impl_linux-64=2.45
  - binutils_linux-64=2.45
  - bleach=6.3.0
  - bleach-with-css=6.3.0
  - blinker=1.9.0
  - blosc=1.21.6
  - bokeh=3.8.1
  - bolt-python=0.7.1
  - boltons=25.0.0
  - boto=2.49.0
  - boto3=1.42.15
  - botocore=1.42.15
  - bottleneck=1.6.0
  - branca=0.8.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brotlicffi=1.2.0.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - c-blosc2=2.15.2
  - c-compiler=1.11.0
  - ca-certificates=2025.11.12
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - cartopy=0.25.0
  - catboost=1.2.8
  - certifi=2025.11.12
  - cffi=2.0.0
  - cftime=1.6.4
  - charset-normalizer=3.4.4
  - clarabel=0.11.1
  - click=8.3.1
  - click-plugins=1.1.1.2
  - cligj=0.7.2
  - clikit=0.6.2
  - cloudpickle=3.1.2
  - coin-or-cbc=2.10.12
  - coin-or-cgl=0.60.9
  - coin-or-clp=1.17.10
  - coin-or-osi=0.108.11
  - coin-or-utils=2.11.12
  - colorama=0.4.6
  - colorcet=3.1.0
  - colorlog=6.10.1
  - comm=0.2.3
  - compilers=1.11.0
  - conda=25.11.1
  - conda-gcc-specs=14.3.0
  - conda-libmamba-solver=25.11.0
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.12.0
  - configargparse=1.7.1
  - contourpy=1.3.2
  - coreforecast=0.0.16
  - coverage=7.13.0
  - cpp-expected=1.3.1
  - cpython=3.10.19
  - cryptography=46.0.3
  - cuda-cudart=12.9.79
  - cuda-cudart_linux-64=12.9.79
  - cuda-nvrtc=12.9.86
  - cuda-nvtx=12.9.79
  - cuda-version=12.9
  - cvxopt=1.3.2
  - cvxpy=1.7.5
  - cvxpy-base=1.7.5
  - cxx-compiler=1.11.0
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - cython=3.2.3
  - cytoolz=1.1.0
  - dask=2025.12.0
  - dask-core=2025.12.0
  - dataclasses=0.8
  - dataclasses-json=0.6.7
  - datasets=2.2.1
  - datashader=0.18.2
  - dav1d=1.2.1
  - dbus=1.16.2
  - debugpy=1.8.19
  - decorator=5.2.1
  - defusedxml=0.7.1
  - deprecated=1.3.1
  - descartes=1.1.0
  - dill=0.4.0
  - distributed=2025.12.0
  - distro=1.9.0
  - dm-tree=0.1.9
  - docutils=0.22.4
  - double-conversion=3.3.1
  - dsdp=5.8
  - ecos=2.0.14
  - einops=0.8.1
  - eo-learn=0.10.1
  - eo-learn-core=1.4.2
  - eo-learn-coregistration=1.4.2
  - eo-learn-features=1.4.2
  - eo-learn-geometry=0.10.1
  - eo-learn-io=0.10.0
  - eo-learn-mask=1.4.2
  - eo-learn-ml-tools=1.4.2
  - eo-learn-visualization=1.3.1
  - epoxy=1.5.10
  - et_xmlfile=2.0.0
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - farama-notifications=0.0.4
  - feather-format=0.4.1
  - ffmpeg=7.1.1
  - fftw=3.3.10
  - filelock=3.20.1
  - fiona=1.10.1
  - flatbuffers=24.12.23
  - fmt=11.2.0
  - folium=0.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.1
  - formulaic=1.2.1
  - fortran-compiler=1.11.0
  - fqdn=1.5.1
  - freeglut=3.2.2
  - freetds=1.5.10
  - freetype=2.14.1
  - freexl=2.0.0
  - fribidi=1.0.16
  - frozendict=2.4.7
  - frozenlist=1.7.0
  - fs=2.4.16
  - fs-s3fs=1.1.1
  - fsspec=2025.12.0
  - fugue=0.9.3
  - gast=0.7.0
  - gcc=14.3.0
  - gcc_impl_linux-64=14.3.0
  - gcc_linux-64=14.3.0
  - gdal=3.10.3
  - gdk-pixbuf=2.42.12
  - gensim=4.3.3
  - geographiclib=2.1
  - geopandas=1.1.2
  - geopandas-base=1.1.2
  - geoplotlib=0.3.2
  - geopy=2.4.1
  - geos=3.14.0
  - geotiff=1.7.4
  - geoviews=1.15.0
  - geoviews-core=1.15.0
  - gflags=2.2.2
  - gfortran=14.3.0
  - gfortran_impl_linux-64=14.3.0
  - gfortran_linux-64=14.3.0
  - giflib=5.2.2
  - gitdb=4.0.12
  - gitpython=3.1.45
  - glib-tools=2.84.3
  - glog=0.7.1
  - glpk=5.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - google-pasta=0.2.0
  - graphite2=1.3.14
  - graphviz=13.1.2
  - greenlet=3.3.0
  - grpcio=1.67.1
  - gsl=2.7
  - gtk3=3.24.43
  - gts=0.7.6
  - gxx=14.3.0
  - gxx_impl_linux-64=14.3.0
  - gxx_linux-64=14.3.0
  - gymnasium=1.2.2
  - h11=0.16.0
  - h2=4.3.0
  - h5netcdf=1.7.3
  - h5py=3.13.0
  - harfbuzz=11.4.5
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hf-xet=1.2.1
  - hicolor-icon-theme=0.17
  - holoviews=1.22.1
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpstan=4.6.1
  - httpx=0.28.1
  - huggingface_hub=0.36.0
  - hvplot=0.12.2
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - igraph=0.10.16
  - imagecodecs-lite=2019.12.3
  - imageio=2.37.0
  - imath=3.1.12
  - imbalanced-learn=0.14.1
  - imgaug=0.4.0
  - importlib-metadata=8.7.0
  - importlib_metadata=8.7.0
  - importlib_resources=6.5.2
  - inflate64=1.0.4
  - iniconfig=2.3.0
  - interface_meta=1.3.0
  - ipykernel=7.1.0
  - ipyleaflet=0.20.0
  - ipympl=0.9.8
  - ipyparallel=9.0.2
  - ipython=8.37.0
  - ipywidgets=8.1.8
  - isoduration=20.11.0
  - jasper=4.2.8
  - jax-jumpy=1.0.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jiter=0.12.0
  - jmespath=1.0.1
  - joblib=1.5.3
  - json-c=0.18
  - jsonpatch=1.33
  - jsonpickle=4.1.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter-server-mathjax=0.2.6
  - jupyter_client=8.7.0
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_leaflet=0.20.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab-git=0.51.3
  - jupyterlab_pygments=0.3.0
  - jupyterlab_widgets=3.0.16
  - kaldi=5.5.1112
  - keras=3.12.0
  - kernel-headers_linux-64=5.14.0
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lame=3.100
  - lark=1.3.1
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.17
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - level-zero=1.26.3
  - libabseil=20240722.0
  - libaec=1.1.4
  - libamd=3.3.3
  - libarchive=3.8.1
  - libarrow=19.0.1
  - libarrow-acero=19.0.1
  - libarrow-dataset=19.0.1
  - libarrow-substrait=19.0.1
  - libasprintf=0.25.1
  - libass=0.17.3
  - libavif16=1.3.0
  - libblas=3.11.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libbtf=2.3.2
  - libcamd=3.3.3
  - libcap=2.77
  - libcblas=3.11.0
  - libccolamd=3.3.4
  - libcholmod=5.3.1
  - libclang-cpp20.1=20.1.8
  - libclang13=21.1.0
  - libcolamd=3.3.4
  - libcrc32c=1.1.2
  - libcublas=12.9.1.4
  - libcufft=11.4.1.4
  - libcups=2.3.3
  - libcurand=10.3.10.19
  - libcurl=8.17.0
  - libcusolver=11.7.5.82
  - libcusparse=12.5.10.65
  - libcxsparse=4.4.1
  - libdeflate=1.24
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libegl-devel=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.4.6
  - libflac=1.5.0
  - libflint=3.2.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-devel_linux-64=14.3.0
  - libgcc-ng=15.2.0
  - libgd=2.3.3
  - libgdal-core=3.10.3
  - libgettextpo=0.25.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libgl-devel=1.7.0
  - libglib=2.84.3
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libglx-devel=1.7.0
  - libgomp=15.2.0
  - libgoogle-cloud=2.36.0
  - libgoogle-cloud-storage=2.36.0
  - libgrpc=1.67.1
  - libhwloc=2.12.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - libklu=2.3.5
  - libkml=1.3.0
  - liblapack=3.11.0
  - liblapacke=3.11.0
  - libldl=3.3.2
  - liblightgbm=4.6.0
  - libllvm20=20.1.8
  - libllvm21=21.1.0
  - liblzma=5.8.1
  - libmagma=2.9.0
  - libmagma_sparse=2.9.0
  - libmamba=2.3.2
  - libmambapy=2.3.2
  - libml_dtypes-headers=0.5.4
  - libnetcdf=4.9.2
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libnvjitlink=12.9.86
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopencv=4.11.0
  - libopengl=1.7.0
  - libopentelemetry-cpp=1.18.0
  - libopentelemetry-cpp-headers=1.18.0
  - libopenvino=2025.0.0
  - libopenvino-auto-batch-plugin=2025.0.0
  - libopenvino-auto-plugin=2025.0.0
  - libopenvino-hetero-plugin=2025.0.0
  - libopenvino-intel-cpu-plugin=2025.0.0
  - libopenvino-intel-gpu-plugin=2025.0.0
  - libopenvino-intel-npu-plugin=2025.0.0
  - libopenvino-ir-frontend=2025.0.0
  - libopenvino-onnx-frontend=2025.0.0
  - libopenvino-paddle-frontend=2025.0.0
  - libopenvino-pytorch-frontend=2025.0.0
  - libopenvino-tensorflow-frontend=2025.0.0
  - libopenvino-tensorflow-lite-frontend=2025.0.0
  - libopus=1.6
  - libosqp=0.6.3
  - libparquet=19.0.1
  - libparu=1.0.0
  - libpciaccess=0.18
  - libpng=1.6.53
  - libpq=17.7
  - libprotobuf=5.28.3
  - libqdldl=0.1.7
  - librbio=4.3.4
  - libre2-11=2024.07.02
  - librosa=0.11.0
  - librsvg=2.58.4
  - librttopo=1.1.0
  - libsanitizer=14.3.0
  - libsndfile=1.2.2
  - libsodium=1.0.20
  - libsolv=0.7.35
  - libspatialite=5.1.0
  - libspex=3.2.3
  - libspqr=4.3.4
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=14.3.0
  - libstdcxx-ng=15.2.0
  - libsuitesparseconfig=7.10.1
  - libsystemd0=258.3
  - libtensorflow_cc=2.18.0
  - libtensorflow_framework=2.18.0
  - libthrift=0.21.0
  - libtiff=4.7.1
  - libtorch=2.6.0
  - libudev1=258.3
  - libumfpack=6.3.5
  - libunwind=1.8.3
  - liburing=2.12
  - libusb=1.0.29
  - libutf8proc=2.10.0
  - libuuid=2.41.3
  - libuv=1.51.0
  - libva=2.23.0
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libvulkan-loader=1.4.328.1
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxgboost=3.1.2
  - libxkbcommon=1.11.0
  - libxml2=2.13.9
  - libxslt=1.1.43
  - libzip=1.11.2
  - libzlib=1.3.1
  - lifelines=0.30.0
  - lightgbm=4.6.0
  - lime=0.2.0.1
  - linkify-it-py=2.0.3
  - llvm-openmp=21.1.8
  - llvmlite=0.46.0
  - locket=1.0.0
  - lxml=6.0.2
  - lz4=4.4.5
  - lz4-c=1.10.0
  - lzo=2.10
  - magma=2.9.0
  - mako=1.3.10
  - mamba=2.3.2
  - mapclassify=2.8.1
  - markdown=3.10
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - marshmallow=3.26.1
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - mdit-py-plugins=0.5.0
  - mdurl=0.1.2
  - menuinst=2.4.2
  - metakernel=0.30.4
  - metis=5.1.0
  - minizip=4.0.10
  - missingno=0.5.2
  - mistune=3.1.4
  - ml_dtypes=0.4.0
  - mlxtend=0.24.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - msgpack-python=1.1.2
  - multidict=6.7.0
  - multipledispatch=0.6.0
  - multiprocess=0.70.18
  - multivolumefile=0.2.3
  - munkres=1.1.4
  - mypy_extensions=1.1.0
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - namex=0.1.0
  - narwhals=2.14.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbdime=4.0.2
  - nbformat=5.10.4
  - nbval=0.11.0
  - nccl=2.28.9.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - netcdf4=1.7.2
  - networkx=3.4.2
  - nibabel=5.3.2
  - nilearn=0.12.1
  - nlohmann_json=3.12.0
  - nlohmann_json-abi=3.12.0
  - nltk=3.9.2
  - nomkl=1.0
  - nose=1.3.7
  - numba=0.63.1
  - numexpr=2.14.1
  - numpy=1.26.4
  - oauthlib=3.3.1
  - ocl-icd=2.3.3
  - openai=2.14.0
  - opencl-headers=2025.06.13
  - opencv=4.11.0
  - openeo=0.46.0
  - openexr=3.3.5
  - openfst=1.8.3
  - openh264=2.6.0
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openpyxl=3.1.5
  - openssl=3.6.0
  - opt_einsum=3.4.0
  - optree=0.18.0
  - optuna=4.6.0
  - orc=2.1.1
  - osqp=0.6.7.post3
  - overrides=7.7.0
  - owslib=0.35.0
  - packaging=25.0
  - pandas=2.3.3
  - pandas-datareader=0.10.0
  - pandocfilters=1.5.0
  - panel=1.8.4
  - pango=1.56.4
  - param=2.3.1
  - parso=0.8.5
  - partd=1.4.2
  - pastel=0.2.1
  - patsy=1.0.2
  - pbr=7.0.3
  - pcre2=10.45
  - pdfminer.six=20251107
  - pdfplumber=0.11.8
  - peft=0.18.0
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.1
  - plotly=6.5.0
  - pluggy=1.6.0
  - ply=3.11
  - pmdarima=2.0.4
  - pooch=1.8.2
  - portalocker=3.2.0
  - proj=9.6.2
  - prometheus-cpp=1.3.0
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - propcache=0.3.1
  - protobuf=5.28.3
  - psutil=7.1.3
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.15
  - pulp=2.8.0
  - pulseaudio-client=17.0
  - pure_eval=0.2.3
  - py-cpuinfo=9.0.0
  - py-opencv=4.11.0
  - py-xgboost=3.1.2
  - py7zr=1.0.0
  - pyaml=25.7.0
  - pyarrow=19.0.1
  - pyarrow-core=19.0.1
  - pybcj=1.0.7
  - pybind11=2.13.6
  - pybind11-abi=4
  - pybind11-global=2.13.6
  - pycosat=0.6.6
  - pycox=0.3.0
  - pycparser=2.22
  - pycryptodomex=3.23.0
  - pyct=0.6.0
  - pydantic=2.12.5
  - pydantic-core=2.41.5
  - pydot=4.0.1
  - pydotplus=2.0.2
  - pydub=0.25.1
  - pyepsg=0.4.0
  - pyglet=2.1.11
  - pygments=2.19.2
  - pyjwt=2.10.1
  - pylev=1.4.0
  - pyodbc=5.3.0
  - pyogrio=0.11.0
  - pyparsing=3.3.1
  - pypdfium2=4.30.1
  - pyppmd=1.1.0
  - pyproj=3.7.1
  - pyshp=3.0.3
  - pysimdjson=7.0.2
  - pysocks=1.7.1
  - pysoundfile=0.13.1
  - pystac=1.14.2
  - pystan=3.10.0
  - pytables=3.10.1
  - pytest=9.0.2
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-flatbuffers=25.9.23
  - python-gil=3.10.19
  - python-graphviz=0.21
  - python-igraph=0.11.9
  - python-infomap=2.8.0
  - python-json-logger=2.0.7
  - python-symengine=0.14.1
  - python-tzdata=2025.3
  - python-xxhash=3.6.0
  - python_abi=3.10
  - pytorch=2.6.0
  - pytz=2025.2
  - pyviz_comms=3.0.6
  - pywavelets=1.8.0
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - pyzstd=0.19.1
  - qdldl-python=0.1.7.post5
  - qhull=2020.2
  - qiskit=2.2.3
  - qiskit-aer=0.17.2
  - qt6-main=6.8.3
  - rasterio=1.4.3
  - rav1e=0.7.1
  - re2=2024.07.02
  - readline=8.3
  - referencing=0.37.0
  - regex=2025.11.3
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - requests=2.32.5
  - requests-oauthlib=2.0.0
  - responses=0.18.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rich=14.2.0
  - rpds-py=0.30.0
  - ruamel.yaml=0.18.17
  - ruamel.yaml.clib=0.2.15
  - rustworkx=0.17.1
  - s2cloudless=1.5.0
  - s2n=1.5.14
  - s3transfer=0.16.0
  - safetensors=0.7.0
  - scikit-image=0.20.0
  - scikit-learn=1.7.2
  - scikit-optimize=0.10.2
  - scikit-plot=0.3.7
  - scikit-survival=0.25.0
  - scipy=1.15.2
  - scs=3.2.9
  - sdl2=2.32.56
  - sdl3=3.2.24
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - sentence-transformers=5.2.0
  - sentinelhub=3.4.4
  - setuptools=80.9.0
  - shap=0.48.0
  - shapely=2.1.2
  - simdjson=4.0.7
  - six=1.17.0
  - sklearn-compat=0.1.5
  - sklearn-pandas=2.2.0
  - sleef=3.9.0
  - slicer=0.0.8
  - smart_open=7.5.0
  - smmap=5.0.2
  - snappy=1.2.2
  - sniffio=1.3.1
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - soupsieve=2.8.1
  - soxr=0.1.3
  - soxr-python=1.0.0
  - spectrum=0.9.0
  - sqlalchemy=2.0.45
  - sqlite=3.51.1
  - stack_data=0.6.3
  - standard-aifc=3.13.0
  - standard-sunau=3.13.0
  - statsforecast=2.0.3
  - statsmodels=0.14.6
  - stevedore=5.6.0
  - suitesparse=7.10.1
  - svt-av1=3.0.2
  - symengine=0.14.0
  - sympy=1.14.0
  - sysroot_linux-64=2.34
  - tabulate=0.9.0
  - tbb=2022.3.0
  - tblib=3.2.2
  - tensorboard=2.18.0
  - tensorboard-data-server=0.7.0
  - tensorflow=2.18.0
  - tensorflow-base=2.18.0
  - tensorflow-estimator=2.18.0
  - tensorflow-hub=0.16.1
  - tensorflow-probability=0.25.0
  - termcolor=3.2.0
  - terminado=0.18.1
  - texttable=1.7.0
  - tf-keras=2.18.0
  - threadpoolctl=3.6.0
  - thunder-python=1.4.2
  - thunder-registration=1.0.1
  - tifffile=2020.6.3
  - tinycss2=1.5.1
  - tk=8.6.13
  - tokenizers=0.22.2
  - tomli=2.3.0
  - toolz=1.1.0
  - torchaudio=2.7.0
  - torchtuples=0.2.2
  - tornado=6.5.4
  - tqdm=4.67.1
  - traitlets=5.14.3
  - traittypes=0.2.3
  - transformers=4.57.3
  - triad=1.0.0
  - truststore=0.10.3
  - tweepy=4.16.0
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - typing_inspect=0.9.0
  - typing_utils=0.1.0
  - tzdata=2025c
  - uc-micro-py=1.0.3
  - unicodedata2=17.0.0
  - unixodbc=2.3.14
  - uri-template=1.3.0
  - uriparser=0.9.8
  - urllib3=2.5.0
  - utilsforecast=0.2.15
  - utm=0.7.0
  - vadersentiment=3.3.2
  - wayland=1.24.0
  - wayland-protocols=1.47
  - wcwidth=0.2.14
  - webargs=8.7.1
  - webcolors=25.10.0
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - werkzeug=3.1.4
  - wheel=0.45.1
  - widgetsnbextension=4.0.15
  - wikipedia-api=0.8.1
  - wordcloud=1.9.4
  - wrapt=1.17.3
  - x264=1!164.3095
  - x265=3.5
  - xarray=2025.1.1
  - xarray-einstats=0.8.0
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.6
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xerces-c=3.2.5
  - xgboost=3.1.2
  - xkeyboard-config=2.46
  - xlrd=2.0.2
  - xlsxwriter=3.2.9
  - xlwt=1.3.0
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxinerama=1.1.5
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxscrnsaver=1.2.4
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2025.1
  - xxhash=0.8.3
  - xyzservices=2025.11.0
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - yarl=1.22.0
  - zeromq=4.3.5
  - zict=3.0.0
  - zipfile-deflate64=0.2.0
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.2.5
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
    - nvidia-cublas-cu12==12.8.4.1
    - nvidia-cuda-cupti-cu12==12.8.90
    - nvidia-cuda-nvrtc-cu12==12.8.93
    - nvidia-cuda-runtime-cu12==12.8.90
    - nvidia-cudnn-cu12==9.10.2.21
    - nvidia-cufft-cu12==11.3.3.83
    - nvidia-cufile-cu12==1.13.1.3
    - nvidia-curand-cu12==10.3.9.90
    - nvidia-cusolver-cu12==11.7.3.90
    - nvidia-cusparse-cu12==12.5.8.93
    - nvidia-cusparselt-cu12==0.7.1
    - nvidia-nccl-cu12==2.27.5
    - nvidia-nvjitlink-cu12==12.8.93
    - nvidia-nvshmem-cu12==3.3.20
    - nvidia-nvtx-cu12==12.8.90
    - torch==2.9.1
    - torchvision==0.24.1
    - triton==3.5.1

prefix: "/m/scicomp/software/scibuilder-mamba/aalto-ubuntu2204/dev/software/jupyter-cs/2026.1/03ad745"
